
spring:
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        trace: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: hichem
    password: hichem
  servlet:
    multipart:
      enabled: true
      max-file-size: 500
      max-request-size: 500
      resolve-lazily: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

debug: true

server:
  port: 8080

